DROP FUNCTION IF EXISTS FN_IS_VALID_NAME;
DELIMITER !
CREATE FUNCTION FN_IS_VALID_NAME(NAME VARCHAR(30))
RETURNS BOOLEAN
BEGIN
	RETURN IF(ISNULL(NAME) OR TRIM(NAME) = "",FALSE,TRUE);
END !
DELIMITER ;

SELECT FN_IS_VALID_NAME("H");



DROP FUNCTION IF EXISTS FN_IS_ALREADY_REGISTERED;
DELIMITER !
CREATE FUNCTION FN_IS_ALREADY_REGISTERED(EMAIL_ID_PARAM VARCHAR(30))
RETURNS BOOLEAN
BEGIN
	RETURN IF((SELECT TRUE FROM USERS WHERE EMAIL_ID = EMAIL_ID_PARAM ) ,TRUE, FALSE);
END !
DELIMITER ;

SELECT FN_IS_ALREADY_REGISTERED("jeevavignesh@gmail.com");
